DELETE http://localhost:3001/api/contacts/697102182e9b4d6633cf97b9

###
POST http://localhost:3001/api/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Ada Lovelace", 
  "number": "39-44-5323523"
}


###
POST http://localhost:3001/api/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Dan Abramov", 
  "number": "867-5309"
}


###
POST http://localhost:3001/api/contacts HTTP/1.1
Content-Type: application/json

{ 
  "name": "Mary Poppendieck", 
  "number": "39-23-6423122"
}

###
POST http://localhost:3001/api/contacts HTTP/1.1
Content-Type: application/json

{ 
  "name": "Cool Gal", 
  "number": "555-5555"
}

###
PUT http://localhost:3001/api/contacts/697251a9c4b2820f72cc5449 HTTP/1.1
Content-Type: application/json

{ 
  "name": "Cool Gal", 
  "number": "39-23-6423122"
}


###
GET http://localhost:3001/api/contacts
